### ISSUE TITLE
Did you do this

### ISSUE THREAD

**Issue by tjw0lf** [3v1lh3x/WebsocketChat#1]
http://dotshare.it/dots/1426/

if so can you tell me how please

**Comment by 3v1lh3x** [comment]
Yep. It's my bash config.
How what ?

**Comment by tjw0lf** [comment]
can you tell me how you did it. I have tried for hours and can't figure it out. I have fontawesome.

setting up your bash like that with the icons

**Comment by 3v1lh3x** [comment]
3v1lh3x@gmail.com write here. I will try to help you

**Comment by tjw0lf** [comment]
sent you the email wolf.tj996@gmail.com this is mine
